Update metadata.rb to fix bug
================================================================================
Recipe Compile Error in /root/chef-solo/cookbooks-1/ulimit/resources/rule.rb
================================================================================

NameError
---------
uninitialized constant Chef::Resource::UlimitDomain

Cookbook Trace:
---------------
  /root/chef-solo/cookbooks-1/ulimit/resources/rule.rb:7:in `class_from_file'

Relevant File Content:
----------------------
/root/chef-solo/cookbooks-1/ulimit/resources/rule.rb:

  1:  actions :create, :delete
  2:  default_action :create
  3:  
  4:  attribute :type, :kind_of => [Symbol,String], :required => true
  5:  attribute :item, :kind_of => [Symbol,String], :required => true
  6:  attribute :value, :kind_of => [String,Numeric], :required => true
  7>> attribute :domain, :kind_of => [Chef::Resource::UlimitDomain, String], :required => true
  8:  

[Tue, 27 Aug 2013 19:36:29 +0000] ERROR: Running exception handlers
[Tue, 27 Aug 2013 19:36:29 +0000] ERROR: Exception handlers complete
[Tue, 27 Aug 2013 19:36:29 +0000] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[Tue, 27 Aug 2013 19:36:29 +0000] FATAL: NameError: uninitialized constant Chef::Resource::UlimitDomain
ERROR: RuntimeError: chef-solo failed. See output above.